### ISSUE TITLE
[October] [Pubs] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditya-nath-sage** [mc2-center/mc2-center-dcc#74]
This ticket tracks curation workflow progression.

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

1. Curation and Annotation

- [x] Run Pubmed crawler to generate PublicationView manifest 
- [ ] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights (https://sagebionetworks.jira.com/browse/CPO-1339)
- [ ] (Aditi) Send Amber "News from CCKP" for MC2 Center Newsletter (https://sagebionetworks.jira.com/browse/CPO-1338)
- [x] Annotate publications in PublicationView manifest [In progress]
- [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
- [ ] (Orion) Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
- [ ] QC of staging tables
- [ ] Performing automate portal sync to CCKP
- [ ] Validate data on the CCKP

Status check [Plan to report numbers for each category following pubmed crawl]:

Publication upload
2. Data model [No new updates]
- [ ] Update valid values in the data model and build
- [ ] Generate templates from new model
- [ ] Release new model version [no changes, no release]
- [ ] Update DCA config [no changes, no update]

**Comment by aditya-nath-sage** [comment]
Ran the Curation workflow scripts (no datasets since I didn't curate them this time).
No issues, should be uploaded!
